### ISSUE TITLE
FrameworkProcessor: `s3_prefix` to be optional

### ISSUE THREAD

**Issue by verdimrc** [verdimrc/sagemaker-python-sdk#2]
**Describe the bug**
`s3_prefix` should be optional, and default to sagemaker default s3 bucket.

**To reproduce**
Python error when not setting `s3_prefix`.

**Expected behavior**
`FrameworkProcessor` to use default sagemaker s3 bucket, same behavior as existing processor.

**Screenshots or logs**
N/A

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: framework-processor branch, this fork repo.

**Comment by athewsey** [comment]
Would also argue the param should be renamed to `code_location` for consistency with estimators.

Current code needs to know a bucket so it can upload `runproc_sh`. If make the param optional we could recover the as-uploaded location from `estimator.uploaded_code` after `self._upload_payload` **HOWEVER**:

...That prop is not set by the Estimator if running in local mode (because it doesn't upload the code at all). So we'll also need to change the way `runproc_sh` is handled downstream to accommodate the fact we might be running in local mode?

**Comment by verdimrc** [comment]
:+1: to test on local mode.

**Comment by athewsey** [comment]
Yes, Processing jobs do work in local mode - as of just last December! https://github.com/aws/sagemaker-python-sdk/pull/1961 If only we'd been a few months earlier it wouldn't be our problem 😂
