### ISSUE TITLE
'test_local_mode_disables_local_code_by_default' fails

### ISSUE THREAD

**Issue by pinak-p** [verdimrc/sagemaker-python-sdk#26]
**Describe the bug**
The unit test `test_local_mode_disables_local_code_by_default` fails. 
Test was introduced in -
PR: https://github.com/verdimrc/sagemaker-python-sdk/pull/22
commit: https://github.com/verdimrc/sagemaker-python-sdk/pull/22/commits/1ed9349d091afdba141ea7419615349aa40938b6

**To reproduce**
`pytest -v  -rA tests/unit/test_processing.py::test_local_mode_disables_local_code_by_default`

**Expected behavior**
The unit test should not fail.

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**:
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:
- **Framework version**:
- **Python version**:
- **CPU or GPU**:
- **Custom Docker image (Y/N)**:

**Additional context**

**Comment by verdimrc** [comment]
To check the unit test on local processor introduced in PR #22

**Comment by verdimrc** [comment]
@pinak-p: the unit test also worked on my environment (so that makes it two with @athewsey). Can you investigate why this local test failed on your environment -- could there be something there that caused this opposite behavior?

```bash
% pytest tests/unit/test_processing.py::test_local_mode_disables_local_code_by_default            
=============================================== test session starts ================================================
platform darwin -- Python 3.9.1, pytest-6.0.2, py-1.10.0, pluggy-0.13.1
rootdir: /Users/marcverd/src/github/sagemaker-python-sdk, configfile: tox.ini
plugins: rerunfailures-9.1.1, cov-2.11.1, xdist-2.2.1, timeout-1.4.2, forked-1.3.0
collected 1 item                                                                                                   

tests/unit/test_processing.py .                                                                              [100%]

================================================ 1 passed in 0.20s =================================================
```

I'll also link this to issue #28 as the whole `tests/unit/test_processing.py` is broken, as opposed to what you got.

**Comment by verdimrc** [comment]
Linked to the tensorflow PR https://github.com/verdimrc/sagemaker-python-sdk/pull/25 that possibly break unit tests.

**Comment by verdimrc** [comment]
Turns out that the test works only if there's a file `~/.aws/config` and region is set. Need to fix this.

**Comment by athewsey** [comment]
Hey sorry to be late on this one & to introduce it!

I first looked at implementing this test by mock patching a Session class (which the other unit tests do), but the challenge I came up against was that you'd need to somehow patch `sagemaker.local.LocalSession` **before** the module(s) under test get imported - since for example importing `processing.py` also does `from sagemaker.local import LocalSession`.

The framework (estimator) also performs an `isinstance` check on the session, so you'd need to patch `LocalSession` with a [method like this](https://stackoverflow.com/a/49718531/13352657) and have that patch applied before the estimator module is imported too - not just the `processing.py`... Or perhaps pass in a mocked-out `estimator_cls` as well?

**Comment by athewsey** [comment]
It's difficult for me to reproduce the issue on my environment - but I think this alternative test might work... Could somebody check & confirm?

```python
@patch("sagemaker.local.LocalSession.__init__", return_value=None)
def test_local_mode_disables_local_code_by_default(localsession_mock):
    Processor(
        image_uri="",
        role=ROLE,
        instance_count=1,
        instance_type="local",
    )

    # Most tests use a fixture for sagemaker_session for consistent behaviour, so this unit test
    # checks that the default initialization disables unsupported 'local_code' mode:
    localsession_mock.assert_called_with(disable_local_code=True)
```

**Comment by verdimrc** [comment]
thanks @athewsey , I'll pick it up sometime today.

**Comment by verdimrc** [comment]
Worked like a charm.

**Comment by verdimrc** [comment]
Closed after PR. Thanks @athewsey for the fix.
